services:
  - type: web
    name: axs-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
